# Development docker-compose file for aquarium
#
# Extends the base docker-compose.yml file with details for the development
# environment.
#
# See the file docker-compose.yml for details on changing or resetting the
# database.
#

version: "3.5"
services:
  app:
    build:
      context: .
      target: aquarium-development
    image: aquarium-development
    command: ["development"]
    volumes:
      - ./app:/aquarium/app
      - ./config:/aquarium/config   
      - ./docs:/aquarium/docs
      - ./lib:/aquarium/lib
      - ./spec:/aquarium/spec
      - ./test:/aquarium/test
      - ./ui:/aquarium/ui
      - ./Gemfile.lock:/aquarium/Gemfile.lock
      - ./package.json:/aquarium/package.json
      - ./yarn.lock:/aquarium/yarn.lock
      - ./.rubocop.yml:/aquarium/.rubocop.yml
      - ./.rubocop_todo.yml:/aquarium/.rubocop_todo.yml

  krill:
    image: aquarium-development
    command: ["krill", "development"]
    volumes:
      - ./config:/aquarium/config   
      - ./lib:/aquarium/lib

  web:
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - "3000:3000"
    volumes:
      - ./docker/nginx.development.conf:/etc/nginx/conf.d/default.conf:ro
