# Development docker-compose file for aquarium
#
# Extends the base docker-compose.yml file with details for the development
# environment.
#
# See the file docker-compose.yml for details on changing or resetting the
# database.
#

version: "3.5"
services:
  app:
    build:
      context: .
      target: aquarium
    image: aquarium
    command: ["development"]
    volumes:
      - ./app:/aquarium/app
      - ./docs:/aquarium/docs
      - ./lib:/aquarium/lib
      - ./spec:/aquarium/spec
      - ./test:/aquarium/test
      - ./ui:/aquarium/ui
      - ./docker/aquarium/database.yml:/aquarium/config/database.yml
      - ./docker/aquarium/aquarium.rb:/aquarium/config/initializers/aquarium.rb
      - ./docker/aquarium/development.rb:/aquarium/config/environments/development.rb
      - ./Gemfile.lock:/aquarium/Gemfile.lock
      - ./yarn.lock:/aquarium/yarn.lock

  krill:
    image: aquarium
    command: ["development"]
    volumes:
      - ./lib:/aquarium/lib
      - ./docker/aquarium/database.yml:/aquarium/config/database.yml
      - ./docker/aquarium/aquarium.rb:/aquarium/config/initializers/aquarium.rb
      - ./docker/aquarium/development.rb:/aquarium/config/environments/development.rb

  web:
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - "3000:3000"
    volumes:
      - ./docker/nginx.development.conf:/etc/nginx/conf.d/default.conf:ro

  ola_image_processing:
    expose:
      - "5000"
    volumes:
      - ./ola_image_processing:/ola_image_processing